name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.github-pages-deploy.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        id: github-pages-deploy
        run: |
          npm install -g gh-pages
          gh-pages -d dist

          echo "Deployed to ${{ steps.github-pages-deploy.outputs.page_url }}"